universe = docker
docker_image = astral/uv:debian
executable = mole_demo.sh
output = logs/mole_demo.$(ClusterId).$(ProcId).out
error = logs/mole_demo.$(ClusterId).$(ProcId).err
log = logs/mole_demo.$(ClusterId).$(ProcId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 6
request_memory = 32GB
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
max_idle = 100
